version: '3.3'
services:
  courses:
    image: jdvelasq/spark-on-r:2019-2
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8888:8888"
      - "9000:9000"
    volumes:
      - type: bind
        source: "$PWD"
        target: /app